name: fitbud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

 # Utility Packages
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2
  pinput: ^5.0.2
  file_picker: ^10.3.7
  salomon_bottom_bar: ^3.3.2
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.2.1
  video_player: ^2.10.1
  path_provider: ^2.1.5

 # Icons
  flutter_lucide: ^1.7.0
  iconsax: ^0.0.8

 # State Management
  get: ^4.7.3

 # Product Specific
  dotted_border: ^3.1.0
  mobile_scanner: ^7.1.3


 # FireBase
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_functions: ^5.6.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0








  #--------------- ./ PACKAGES END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true



  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/




  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900